
CREATE TABLE USERS_DETAILS
(
U_ID VARCHAR(10) NOT NULL,
F_NAME VARCHAR(10),
L_NAME VARCHAR(10),
CITY VARCHAR(10),
STREET VARCHAR(10),
PHONE VARCHAR(12),
PRIMARY KEY (U_ID));

CREATE TABLE GENRE
(
G_ID VARCHAR(10) NOT NULL,
NAME VARCHAR(10),
PRIMARY KEY(G_ID)); 

CREATE TABLE BOOKS_DETAILS
(
ISBN VARCHAR(10) NOT NULL,
TITLE VARCHAR(25),
AUTHOR VARCHAR(15),
RATING INT,
G_ID VARCHAR(10), 
POSITION VARCHAR(10),
DISCOUNT INT,
PRIMARY KEY (ISBN),
FOREIGN KEY(G_ID) REFERENCES GENRE(G_ID) ON DELETE CASCADE);

CREATE TABLE CUSTOMER
(
CUST_ID VARCHAR(10) NOT NULL,
TYPE VARCHAR(10),
PRIMARY KEY (CUST_ID),
FOREIGN KEY(CUST_ID) REFERENCES USERS_DETAILS(U_ID) ON DELETE CASCADE);

CREATE TABLE STAFF
(
S_ID VARCHAR(10) NOT NULL,
SALARY INT,
PRIMARY KEY (S_ID),
FOREIGN KEY(S_ID) REFERENCES USERS_DETAILS(U_ID) ON DELETE CASCADE);

CREATE TABLE PURCHASE
(
P_ID VARCHAR(10) NOT NULL,
U_ID VARCHAR(10) NOT NULL,
ISBN VARCHAR(10),
P_DATE DATE,
PRICE FLOAT(5),
PRIMARY KEY(P_ID),
FOREIGN KEY(U_ID) REFERENCES USERS_DETAILS(U_ID) ON DELETE CASCADE,
FOREIGN KEY(ISBN) REFERENCES BOOKS_DETAILS(ISBN) ON DELETE CASCADE);

CREATE TABLE RENT
(
R_ID VARCHAR(10) NOT NULL,
U_ID VARCHAR(10) NOT NULL,
ISBN VARCHAR(10),
R_DATE DATE,
VALID_TILL DATE,
PRICE FLOAT(5),
PRIMARY KEY(R_ID),
FOREIGN KEY(U_ID) REFERENCES USERS_DETAILS(U_ID) ON DELETE CASCADE,
FOREIGN KEY(ISBN) REFERENCES BOOKS_DETAILS(ISBN) ON DELETE CASCADE);


CREATE TABLE PUBLISHER
(
PUB_ID VARCHAR(10) NOT NULL,
ISBN VARCHAR(10) NOT NULL,
NAME VARCHAR(15),
EDITION INT,
PRIMARY KEY (ISBN),
FOREIGN KEY(ISBN) REFERENCES BOOKS_DETAILS(ISBN) ON DELETE CASCADE);

CREATE TABLE LOGIN_DETAILS
(
U_ID VARCHAR(10) NOT NULL,
PASSWORD VARCHAR(10) NOT NULL,
PRIMARY KEY (U_ID), 
FOREIGN KEY (U_ID) REFERENCES USERS_DETAILS(U_ID) ON DELETE CASCADE);


CREATE TABLE COPY
(
COPY_ID VARCHAR(10) NOT NULL,
ISBN VARCHAR(10),
TYPE VARCHAR(10),
PRICE FLOAT(5),
PRIMARY KEY (COPY_ID),
FOREIGN KEY (ISBN) REFERENCES BOOKS_DETAILS(ISBN) ON DELETE CASCADE);


CREATE VIEW DAILY_PURCHASE (DATE_OF_PURCHASE,NO_OF_PURCHASES,TOTAL_AMOUNT)
AS SELECT P_DATE,COUNT(*),SUM(PRICE)
FROM PURCHASE
WHERE P_DATE=CURRENT_DATE
GROUP BY P_DATE;
